import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';

// Vite ke sath pdfmake fonts ko initialize karna
if (pdfFonts && pdfFonts.pdfMake) {
  pdfMake.vfs = pdfFonts.pdfMake.vfs;
} else {
  pdfMake.vfs = window.pdfMake ? window.pdfMake.vfs : pdfFonts.vfs;
}

export const generateInvoicePDF = (order, customer, shop) => {
  // 1. Calculations
  const totalBill = order.items.reduce((sum, item) => sum + (item.price * item.quantity), 0);
  const totalPaid = order.payments?.reduce((sum, pay) => sum + pay.installmentAmount, 0) || 0;
  const pendingAmount = totalBill - totalPaid;

  const orderDate = new Date(order.createdAt).toLocaleDateString('en-IN');
  const deliveryDate = new Date(order.deliveryDate).toLocaleDateString('en-IN');
  
  const garmentType = order.items[0]?.garmentType || 'Garment';

  // 2. Grahak ka is kapde se juda aakhiri naap nikalna
  const relatedMeasurement = customer.measurements?.find(m => m.garmentType === garmentType);
  
  // Measurement Data ko table format me laana
  let measurementBody = [];
  if (relatedMeasurement && relatedMeasurement.data) {
    const mData = Object.entries(relatedMeasurement.data);
    // 2-2 column me naap dikhane ke liye chunking
    for (let i = 0; i < mData.length; i += 2) {
      const row = [];
      row.push({ text: mData[i][0], bold: true, fontSize: 10, color: '#555' });
      row.push({ text: mData[i][1] + '"', fontSize: 10 });
      if (mData[i + 1]) {
        row.push({ text: mData[i + 1][0], bold: true, fontSize: 10, color: '#555' });
        row.push({ text: mData[i + 1][1] + '"', fontSize: 10 });
      } else {
        row.push('', ''); // Khali cells table balance karne ke liye
      }
      measurementBody.push(row);
    }
  }

  // 3. PDF Document Definition (Design)
  const docDefinition = {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 60], // Left, Top, Right, Bottom
    
    // Footer: Har page ke neeche aayega
    footer: function(currentPage, pageCount) {
      return {
        text: 'Generated by Tailor Management System',
        alignment: 'center',
        fontSize: 9,
        color: '#9CA3AF',
        margin: [0, 20, 0, 0]
      };
    },

    content: [
      // --- HEADER SECTION ---
      {
        columns: [
          {
            width: '*',
            text: shop.shopName || 'Premium Tailors',
            fontSize: 26,
            bold: true,
            color: '#4F46E5', // Primary App Color
            margin: [0, 0, 0, 5]
          },
          {
            width: 'auto',
            text: [
              { text: 'INVOICE\n', fontSize: 20, bold: true, color: '#111827' },
              { text: `#${order.orderNumber}`, fontSize: 12, color: '#6B7280' }
            ],
            alignment: 'right'
          }
        ]
      },
      {
        text: `Proprietor: ${shop.name}\nMob: +91 ${shop.mobile}\n${shop.shopAddress || ''}`,
        fontSize: 10,
        color: '#4B5563',
        margin: [0, 0, 0, 20]
      },
      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: '#E5E7EB' }] },
      
      // --- CUSTOMER & ORDER INFO SECTION ---
      {
        columns: [
          {
            width: '50%',
            stack: [
              { text: 'Bill To:', fontSize: 10, bold: true, color: '#9CA3AF', margin: [0, 15, 0, 5] },
              { text: customer.name, fontSize: 14, bold: true, color: '#111827' },
              { text: `Mobile: +91 ${customer.mobile}`, fontSize: 10, color: '#4B5563', margin: [0, 2, 0, 0] },
              { text: `Customer ID: ${customer.customerCode}`, fontSize: 10, color: '#4B5563', margin: [0, 2, 0, 0] }
            ]
          },
          {
            width: '50%',
            alignment: 'right',
            stack: [
              { text: 'Order Details:', fontSize: 10, bold: true, color: '#9CA3AF', margin: [0, 15, 0, 5] },
              { text: `Booking Date: ${orderDate}`, fontSize: 10, color: '#4B5563' },
              { text: `Delivery Date: ${deliveryDate}`, fontSize: 10, bold: true, color: '#4F46E5', margin: [0, 2, 0, 0] },
              { text: `Status: ${order.status}`, fontSize: 10, color: '#4B5563', margin: [0, 2, 0, 0] }
            ]
          }
        ]
      },

      // --- MEASUREMENT SECTION (Agar available ho) ---
      relatedMeasurement ? {
        margin: [0, 25, 0, 0],
        stack: [
          { text: `Measurements (${garmentType})`, fontSize: 12, bold: true, color: '#111827', margin: [0, 0, 0, 8] },
          {
            table: {
              widths: ['25%', '25%', '25%', '25%'],
              body: measurementBody
            },
            layout: {
              hLineWidth: () => 0.5,
              vLineWidth: () => 0.5,
              hLineColor: () => '#E5E7EB',
              vLineColor: () => '#E5E7EB',
              paddingLeft: () => 8,
              paddingRight: () => 8,
              paddingTop: () => 6,
              paddingBottom: () => 6,
            }
          }
        ]
      } : { text: '' }, // Khali text agar naap na ho

      // --- ORDER ITEMS SECTION ---
      { text: 'Order Items', fontSize: 12, bold: true, color: '#111827', margin: [0, 25, 0, 8] },
      {
        table: {
          headerRows: 1,
          widths: ['*', 'auto', 'auto', 'auto'],
          body: [
            [
              { text: 'Item Description', bold: true, fontSize: 10, fillColor: '#F3F4F6', border: [false, false, false, true] },
              { text: 'Qty', bold: true, fontSize: 10, alignment: 'center', fillColor: '#F3F4F6', border: [false, false, false, true] },
              { text: 'Rate', bold: true, fontSize: 10, alignment: 'right', fillColor: '#F3F4F6', border: [false, false, false, true] },
              { text: 'Total', bold: true, fontSize: 10, alignment: 'right', fillColor: '#F3F4F6', border: [false, false, false, true] },
            ],
            ...order.items.map(item => [
              { text: item.garmentType + (item.notes ? `\n(${item.notes})` : ''), fontSize: 10, border: [false, false, false, true], borderColor: ['#E5E7EB'] },
              { text: item.quantity.toString(), fontSize: 10, alignment: 'center', border: [false, false, false, true], borderColor: ['#E5E7EB'] },
              { text: `Rs ${item.price}`, fontSize: 10, alignment: 'right', border: [false, false, false, true], borderColor: ['#E5E7EB'] },
              { text: `Rs ${item.price * item.quantity}`, fontSize: 10, alignment: 'right', border: [false, false, false, true], borderColor: ['#E5E7EB'] }
            ])
          ]
        }
      },

      // --- PAYMENT SUMMARY SECTION ---
      {
        columns: [
          { width: '*', text: '' }, // Khali space left me
          {
            width: '40%',
            margin: [0, 15, 0, 0],
            table: {
              widths: ['*', 'auto'],
              body: [
                [
                  { text: 'Total Bill:', fontSize: 11, bold: true, color: '#4B5563', border: [false, false, false, false], alignment: 'right' },
                  { text: `Rs ${totalBill}`, fontSize: 11, bold: true, color: '#111827', border: [false, false, false, false], alignment: 'right' }
                ],
                [
                  { text: 'Advance Paid:', fontSize: 11, color: '#059669', border: [false, false, false, false], alignment: 'right' },
                  { text: `Rs ${totalPaid}`, fontSize: 11, color: '#059669', border: [false, false, false, false], alignment: 'right' }
                ],
                [
                  { text: 'Pending Balance:', fontSize: 12, bold: true, color: '#DC2626', border: [false, true, false, false], borderColor: ['#E5E7EB'], alignment: 'right', margin: [0, 5, 0, 0] },
                  { text: `Rs ${pendingAmount}`, fontSize: 12, bold: true, color: '#DC2626', border: [false, true, false, false], borderColor: ['#E5E7EB'], alignment: 'right', margin: [0, 5, 0, 0] }
                ]
              ]
            }
          }
        ]
      },

      // --- TERMS & CONDITIONS (Optional) ---
      {
        margin: [0, 40, 0, 0],
        text: [
          { text: 'Terms & Conditions:\n', fontSize: 9, bold: true, color: '#4B5563' },
          { text: '1. Kapda delivery receipt dikhane par hi milega.\n2. Silai ke baad koi bada badlav charges ke sath hoga.\n3. Bill generation ki date se 30 din ke baad kapde ki zimmedari dukan ki nahi hogi.', fontSize: 8, color: '#6B7280' }
        ]
      }
    ]
  };

  // PDF Download Trigger
  pdfMake.createPdf(docDefinition).download(`Invoice_${order.orderNumber}.pdf`);
};